In [1]:
import numpy as np

In [2]:
print("numpy version", np.__version__)

numpy version 1.19.2


In [10]:
arr_int=np.array([[1,2,3],[4,5,6]])
print(arr_int)
print("type:", type(arr_int),"shape:", arr_int.shape)
print("axis 0:", arr_int.shape[0], "axis 1:", arr_int.shape[1])

[[1 2 3]
 [4 5 6]]
type: <class 'numpy.ndarray'> shape: (2, 3)
axis 0: 2 axis 1: 3


In [13]:
arr_zeros=np.zeros((2, 3))
print(arr_zeros, arr_zeros.dtype, type(arr_zeros))

[[0. 0. 0.]
 [0. 0. 0.]] float64 <class 'numpy.ndarray'>


In [14]:
arr_ones=np.ones((2, 4))
print(arr_zeros, arr_ones.dtype, type(arr_ones))

[[0. 0. 0.]
 [0. 0. 0.]] float64 <class 'numpy.ndarray'>


In [17]:
arr_arange=np.arange(1, 20, 2) #loncat2
print(arr_arange, arr_arange.dtype, type(arr_arange))

[ 1  3  5  7  9 11 13 15 17 19] int32 <class 'numpy.ndarray'>


In [20]:
arr_empty=np.empty((100,100))
print(arr_empty, arr_empty.dtype, type(arr_empty))

[[7.96260375e-312 7.96256176e-312 6.95250701e-310 ... 3.36700284e-290
              nan 2.08600674e-308]
 [8.01025914e-307             nan 1.66880539e-308 ...             nan
              nan 4.00833672e-291]
 [            nan             nan             nan ...             nan
  3.24924770e-297 3.82525393e-296]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]] float64 <class 'numpy.ndarray'>


In [27]:
dummy_list=[[1,2,3],[4,5,6]]
print("list:", dummy_list)
print("array:", arr_int)

print(dummy_list[0][0], dummy_list[0][:2])
print(arr_int[0,0], arr_int[0,:2])
#print(arr_int[::-1])

list: [[1, 2, 3], [4, 5, 6]]
array: [[1 2 3]
 [4 5 6]]
1 [1, 2]
1 [1 2]


In [29]:
#ndim and size of ndaray
print("num of dimens:", arr_int.ndim)
#print("num of dim:", arr3_int.ndim)
print("total items:", arr_int.size)

num of dimens: 2
total items: 6


In [30]:
#flatten
print("b4 flatte:", arr_int)
print("after flatten", arr_int.flatten())

b4 flatte: [[1 2 3]
 [4 5 6]]
after flatten [1 2 3 4 5 6]


In [38]:
#append, concatenate and delete
print(np.append(arr_int,[[10,11,12]], axis=0))
#ambil axis ke 0 

print(np.append(arr_int,[[10],[11]], axis=1))
print 

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]]


In [44]:
#reshape
print(arr3d_int)
print(np.reshape(arr3d_int,(3,4)))

[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]

 [[5.  6. ]
  [7.  8. ]
  [0.3 0.4]]]
[[1.  2.  3.  4. ]
 [0.1 0.2 5.  6. ]
 [7.  8.  0.3 0.4]]


In [40]:
arr1d_float = np.array([.1, .2, .3, .4])
print(arr1d_float)
print( "type:", type(arr1d_float), "shape:", arr1d_float.shape)
print("axis 0:", arr1d_float.shape[0])
print(len(arr1d_float))

arr3d_int = np.array([[[1, 2], [3, 4], [.1, .2]], [[5, 6], [7, 8], [.3, .4]]])
print(arr3d_int)
print( "type:", type(arr3d_int), "shape:", arr3d_int.shape)
print(
    "axis 0:", arr3d_int.shape[0],
    "axis 0:", arr3d_int.shape[1],
    "axis 0:", arr3d_int.shape[2]
)
print(len(arr3d_int))


[0.1 0.2 0.3 0.4]
type: <class 'numpy.ndarray'> shape: (4,)
axis 0: 4
4
[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]

 [[5.  6. ]
  [7.  8. ]
  [0.3 0.4]]]
type: <class 'numpy.ndarray'> shape: (2, 3, 2)
axis 0: 2 axis 0: 3 axis 0: 2
2


In [47]:
print(np.resize(arr3d_int,(7,2)))

[[1.  2. ]
 [3.  4. ]
 [0.1 0.2]
 [5.  6. ]
 [7.  8. ]
 [0.3 0.4]
 [1.  2. ]]


In [48]:
...

Ellipsis

In [55]:
arr2d_float=arr1d_float[:, np.newaxis]
print(arr2d_float, arr2d_float.shape)
print(arr1d_float[None])

[[0.1]
 [0.2]
 [0.3]
 [0.4]] (4, 1)
[[0.1 0.2 0.3 0.4]]


In [56]:
print(arr_int)

[[1 2 3]
 [4 5 6]]


In [57]:
print(arr_int.T)
print(arr_int.reshape)

[[1 4]
 [2 5]
 [3 6]]


In [59]:
print(arr_int+arr_int)


[[ 2  4  6]
 [ 8 10 12]]


In [63]:
print(np.round(arr_int/3, decimals=4))

[[0.3333 0.6667 1.    ]
 [1.3333 1.6667 2.    ]]


In [66]:
print(arr_int.sum(axis=1)) #turun jumlahnya
print(arr_int.sum(keepdims=True))

[ 6 15]
[[21]]


In [68]:
np.random.seed(999)

AttributeError: module 'numpy.random' has no attribute 'radint'